/*
     RANGE OPEARTORS
     --> BETWEEN
     --> NOT BETWEEN
     --> IS NULL
     --> IS NOT NULL
*/


-- IS NULL, IS NOT NULL (TO FILTER OUT NULL VALUES)
SELECT * 
FROM person
WHERE SCORE IS NOT NULL

-- BETWEEN, NOT BETWEEN (TO FILTER A RANGE OF VALUES, BOUNDRIES ARE ALWAYS INCLUSIVE; eg: 60 >= and 100 <=)
SELECT * 
FROM person
WHERE SCORE BETWEEN 60 AND 100