/*
	DDL - DATA DEFINITION LANGUAGE(TO CHANGE IN SCHEMA || CREATE AN EMPTY TABLE)
	--> CREATE
	--> ALTER
	--> DROP
*/

CREATE TABLE DDL
(
	ID INT NOT NULL,--WE CAN GIVE IT AS "ID INT NOT NULL PRIMARY KEY" AS WELL TO AVOID 5TH LINE
	NAME VARCHAR(50) NOT NULL,
	AGE INT,
	CITY VARCHAR(50),
	CONSTRAINT PK_DDL PRIMARY KEY (ID) 
)

-- THIS WILL ADD A NEW COLUMN(STATE) TO THE TABLE DDL(JUST CHANGE THE SCHEMA NOT DATA)
ALTER TABLE DDL
	ADD STATE VARCHAR(20)

-- THIS WILL DROP THE COLUMN CITY FROM THE TABLE DDL
ALTER TABLE DDL
DROP COLUMN CITY

-- THIS WILL DROP THE TABLE DDL FROM THE DATABASE
DROP TABLE DDL